project_id = "rzupsyhyoztaekcwmels"

[functions.send-notification]
verify_jwt = true

[functions.ai-model-analysis]
verify_jwt = true

[functions.model-sharing]
verify_jwt = true

[functions.payu-payment]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.solana-payment]
verify_jwt = false